version: '3.5'
networks:
  default:
    name: default2
services:
  besu2:
    image: hyperledger/besu:23.7.2
    command:
      - --config-file
      - /etc/besu/besu.conf
      - --genesis-file
      - /etc/besu/genesis.json
      - --data-path
      - /var/lib/besu/data
      - --rpc-http-host
      - 0.0.0.0
      - --rpc-ws-host
      - 0.0.0.0
      - --metrics-host
      - 0.0.0.0
      - --p2p-host
      - 0.0.0.0
    volumes:
      - "./config.toml:/etc/besu/besu.conf"
      - "./node-2/data:/var/lib/besu/data"
      - "./genesis-2.json:/etc/besu/genesis.json"
    ports:
      - "7545:8545"
