name: CI - R3 Corda/EVM onnly

on:
  push:
    paths:
      - 'src/r3/atomic-swap/**'
  pull_request:
    paths:
      - 'src/r3/atomic-swap/**'  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run R3 harmonia testnet
      run: |
        docker run --platform linux/amd64 -d -p 8545:8545 edoardoierina/r3-harmonia-testnet:latest
        
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean test --continue
        build-root-directory: 'src/r3/atomic-swap/corda'
